[package]
name = "transfer_sol_program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.1"
solana-program = "~1.10.35"

[lib]
name = "transfer_sol_program"
crate-type = ["cdylib", "lib"]
